FROM openjdk

ARG JAR_FILE
ARG GMAIL_USER
ARG GMAIL_PASSWORD

COPY ${JAR_FILE} app.jar
ENV GMAIL_USER=${GMAIL_USER}
ENV GMAIL_PASSWORD=${GMAIL_PASSWORD}

ENTRYPOINT ["java","-jar","/app.jar"]
EXPOSE 8080