spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true